# Generated by Django 2.2.3 on 2019-08-08 21:19

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required.', max_length=60, verbose_name='name')),
                ('cpf_cnpj', models.CharField(error_messages={'unique': 'An applicant with that CPF/CNPJ already exists.'}, help_text='Required.', max_length=20, unique=True, validators=[accounts.validators.NumericValidator()], verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(help_text='Required.', max_length=254, verbose_name='email address')),
                ('phone', models.CharField(help_text='Required.', max_length=20, verbose_name='phone')),
                ('cellphone', models.CharField(max_length=20, verbose_name='cellphone')),
                ('address_name', models.CharField(help_text='Required.', max_length=60, verbose_name='address name')),
                ('address_number', models.CharField(help_text='Required.', max_length=6, validators=[accounts.validators.NumericValidator()], verbose_name='address number')),
                ('address_complement', models.CharField(blank=True, max_length=30, verbose_name='address complement')),
                ('address_neighborhood', models.CharField(help_text='Required.', max_length=30, verbose_name='neighborhood')),
                ('address_city', models.CharField(help_text='Required.', max_length=30, verbose_name='city')),
                ('address_state', models.CharField(help_text='Required.', max_length=30, verbose_name='state')),
                ('address_cep', models.CharField(help_text='Required.', max_length=15, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required.', max_length=60, verbose_name='full name')),
                ('cpf', models.CharField(error_messages={'unique': 'A legal representative with that CPF already exists.'}, help_text='Required.', max_length=15, unique=True, validators=[accounts.validators.NumericValidator()], verbose_name='CPF')),
                ('email', models.EmailField(help_text='Required.', max_length=254, verbose_name='email address')),
                ('phone', models.CharField(help_text='Required.', max_length=20, verbose_name='phone')),
                ('cellphone', models.CharField(max_length=20, verbose_name='cellphone')),
                ('applicant_represented', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_representative', to='applicants.Applicant')),
            ],
        ),
    ]
