# Generated by Django 2.2.3 on 2019-08-08 21:19

import accounts.models
import accounts.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(help_text='Required.', max_length=60, verbose_name='full name')),
                ('rf', models.CharField(error_messages={'unique': 'A user with that RF already exists.'}, help_text='Required.', max_length=15, unique=True, validators=[accounts.validators.NumericValidator()], verbose_name='RF')),
                ('email', models.EmailField(help_text='Required.', max_length=254, verbose_name='email address')),
                ('cpf', models.CharField(error_messages={'unique': 'A user with that CPF already exists.'}, help_text='Required.', max_length=15, unique=True, validators=[accounts.validators.NumericValidator()], verbose_name='CPF')),
                ('rg', models.CharField(error_messages={'unique': 'A user with that RG already exists.'}, help_text='Required.', max_length=15, unique=True, validators=[accounts.validators.NumericValidator()], verbose_name='RG')),
                ('permissions', models.CharField(choices=[('RO', 'read only'), ('RW', 'read and write')], default='RO', max_length=2)),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrator status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
